version: '3'
services: 
  react-app:
    # because our dockerfile has a different name, need to add context 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8000:3000"
    volumes: 
      - /app/node_modules
      # map current folder to app folder inside of container
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
